In [1]:
import numpy as np

In [13]:
A = np.arange(12).reshape(3,4)
print(A)
print(A.shape)
print(A.ndim)
print(A.size)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
2
12


In [18]:
print(A.mean(axis=0))
print(A.sum(axis=1))

[4. 5. 6. 7.]
[ 6 22 38]


In [19]:
print(A.T)
print(A@A.T)
print(A.T@A)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 14  38  62]
 [ 38 126 214]
 [ 62 214 366]]
[[ 80  92 104 116]
 [ 92 107 122 137]
 [104 122 140 158]
 [116 137 158 179]]


In [20]:
print(A*A)
print(A@A.T)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[ 14  38  62]
 [ 38 126 214]
 [ 62 214 366]]
