In [24]:
import numpy as np

A = np.arange(12).reshape(3,4)
print(A)
print(A[0])
print(A[1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2 3]
[4 5 6 7]


In [6]:
print(np.dot(A[0], A[1]))
print(np.dot(A[0], A[2]))
print(np.dot(A[1], A[0]))
print(np.dot(A[1], A[2]))

38
62
38
214


In [10]:
print((A[0]*A[1]).sum())
print(A[0]*A[1])

38
[ 0  5 12 21]


In [27]:
print(A)
print(A.T)

print((A@A.T)[0,0])
print((A@A.T)[0,1])
print((A@A.T)[1,0])
print((A@A.T)[1,1])
print((A@A.T)[0,2])
print((A@A.T)[2,0])
print((A@A.T)[1,2])
print((A@A.T)[2,1])
print((A@A.T)[2,2])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
14
38
38
126
62
62
214
214
366


In [17]:
G = np.zeros((3, 3))
print(G)

for i in range(3):
    for j in range(3):
        G[i, j] = np.dot(A[i], A[j])

print(G)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 14.  38.  62.]
 [ 38. 126. 214.]
 [ 62. 214. 366.]]


In [22]:
print(np.diag(A@A.T))
print(np.diagonal(A@A.T))
print(np.linalg.norm(A[0]))
print(np.linalg.norm(A[1]))
print(np.linalg.norm(A[2]))

print(np.linalg.norm(A, axis=1)**2)

[ 14 126 366]
[ 14 126 366]
3.7416573867739413
11.224972160321824
19.131126469708992
[ 14. 126. 366.]


In [28]:
print((A@A.T)[1,2])
print(np.dot(A[1],A[2]))
print(A[1] * A[2])
print((A[1] * A[2]).sum())

214
214
[32 45 60 77]
214


In [29]:
total = 0
for k in range(4):
    total += A[1][k] * A[2][k]   # 한 자리씩 곱해서 누적
    print(f"{A[1][k]} * {A[2][k]} = {A[1][k]*A[2][k]}, 누적합 = {total}")
print("최종:", total)


4 * 8 = 32, 누적합 = 32
5 * 9 = 45, 누적합 = 77
6 * 10 = 60, 누적합 = 137
7 * 11 = 77, 누적합 = 214
최종: 214


In [32]:
print(A[1] @ A[2])

214


In [33]:
print(A@A.T)


[[ 14  38  62]
 [ 38 126 214]
 [ 62 214 366]]


In [35]:
print(np.allclose(G, G.T))

True


In [41]:
print(A / np.linalg.norm(A, axis=1, keepdims=True))
A_unit = A / np.linalg.norm(A, axis=1, keepdims=True)
print(A_unit)
print(A_unit @ A_unit.T)

[[0.         0.26726124 0.53452248 0.80178373]
 [0.35634832 0.4454354  0.53452248 0.62360956]
 [0.4181667  0.47043754 0.52270837 0.57497921]]
[[0.         0.26726124 0.53452248 0.80178373]
 [0.35634832 0.4454354  0.53452248 0.62360956]
 [0.4181667  0.47043754 0.52270837 0.57497921]]
[[1.         0.9047619  0.86613807]
 [0.9047619  1.         0.99652445]
 [0.86613807 0.99652445 1.        ]]
