In [8]:
import numpy as np

A = np.arange(12).reshape(3, 4)

print(A)

print(np.linalg.norm(A, axis=1, keepdims=True))

A_unit = A / np.linalg.norm(A, axis=1, keepdims=True)

print(A_unit)
print(np.linalg.norm(A_unit, axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 3.74165739]
 [11.22497216]
 [19.13112647]]
[[0.         0.26726124 0.53452248 0.80178373]
 [0.35634832 0.4454354  0.53452248 0.62360956]
 [0.4181667  0.47043754 0.52270837 0.57497921]]
[1. 1. 1.]


In [9]:
print(A_unit @ A_unit.T)
print(np.diag(A_unit @ A_unit.T))

[[1.         0.9047619  0.86613807]
 [0.9047619  1.         0.99652445]
 [0.86613807 0.99652445 1.        ]]
[1. 1. 1.]
