## 연습장


In [15]:
import numpy as np

A = np.arange(12).reshape(3,4)
print(A)
print(A.T)
print(A[0])
print(A.T[0])

print(A@A.T)

G = np.zeros((3,3))

print(G)

for i in range(3):
    for j in range(3):
        print(A[i])
        print(A[j])
        print(A[i] @ A[j])
        G[i, j] = A[i] @ A[j]


print(G)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[0 1 2 3]
[0 4 8]
[[ 14  38  62]
 [ 38 126 214]
 [ 62 214 366]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0 1 2 3]
[0 1 2 3]
14
[0 1 2 3]
[4 5 6 7]
38
[0 1 2 3]
[ 8  9 10 11]
62
[4 5 6 7]
[0 1 2 3]
38
[4 5 6 7]
[4 5 6 7]
126
[4 5 6 7]
[ 8  9 10 11]
214
[ 8  9 10 11]
[0 1 2 3]
62
[ 8  9 10 11]
[4 5 6 7]
214
[ 8  9 10 11]
[ 8  9 10 11]
366
[[ 14.  38.  62.]
 [ 38. 126. 214.]
 [ 62. 214. 366.]]
